//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaxClient.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ManaxClient.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage.Title", resourceCulture);
            }
        }
        
        public static string LoginPage_Subtitle {
            get {
                return ResourceManager.GetString("LoginPage.Subtitle", resourceCulture);
            }
        }
        
        public static string LoginPage_Username {
            get {
                return ResourceManager.GetString("LoginPage.Username", resourceCulture);
            }
        }
        
        public static string LoginPage_Username_Placeholder {
            get {
                return ResourceManager.GetString("LoginPage.Username.Placeholder", resourceCulture);
            }
        }
        
        public static string LoginPage_Password {
            get {
                return ResourceManager.GetString("LoginPage.Password", resourceCulture);
            }
        }
        
        public static string LoginPage_Password_Placeholder {
            get {
                return ResourceManager.GetString("LoginPage.Password.Placeholder", resourceCulture);
            }
        }
        
        public static string LoginPage_Server {
            get {
                return ResourceManager.GetString("LoginPage.Server", resourceCulture);
            }
        }
        
        public static string LoginPage_Server_Placeholder {
            get {
                return ResourceManager.GetString("LoginPage.Server.Placeholder", resourceCulture);
            }
        }
        
        public static string LoginPage_SignIn {
            get {
                return ResourceManager.GetString("LoginPage.SignIn", resourceCulture);
            }
        }
        
        public static string LoginPage_Tip_Title {
            get {
                return ResourceManager.GetString("LoginPage.Tip.Title", resourceCulture);
            }
        }
        
        public static string LoginPage_Tip_Message {
            get {
                return ResourceManager.GetString("LoginPage.Tip.Message", resourceCulture);
            }
        }
        
        public static string ChapterPage_Pages {
            get {
                return ResourceManager.GetString("ChapterPage.Pages", resourceCulture);
            }
        }
        
        public static string ChapterPage_Back {
            get {
                return ResourceManager.GetString("ChapterPage.Back", resourceCulture);
            }
        }
        
        public static string ChapterPage_Previous {
            get {
                return ResourceManager.GetString("ChapterPage.Previous", resourceCulture);
            }
        }
        
        public static string ChapterPage_Chapter {
            get {
                return ResourceManager.GetString("ChapterPage.Chapter", resourceCulture);
            }
        }
        
        public static string ChapterPage_Next {
            get {
                return ResourceManager.GetString("ChapterPage.Next", resourceCulture);
            }
        }
        
        public static string ChapterPage_PreviousPage {
            get {
                return ResourceManager.GetString("ChapterPage.PreviousPage", resourceCulture);
            }
        }
        
        public static string ChapterPage_NextPage {
            get {
                return ResourceManager.GetString("ChapterPage.NextPage", resourceCulture);
            }
        }
        
        public static string HomePage_Welcome {
            get {
                return ResourceManager.GetString("HomePage.Welcome", resourceCulture);
            }
        }
        
        public static string HomePage_Subtitle {
            get {
                return ResourceManager.GetString("HomePage.Subtitle", resourceCulture);
            }
        }
        
        public static string HomePage_AddSeries {
            get {
                return ResourceManager.GetString("HomePage.AddSeries", resourceCulture);
            }
        }
        
        public static string HomePage_NoSeries {
            get {
                return ResourceManager.GetString("HomePage.NoSeries", resourceCulture);
            }
        }
        
        public static string HomePage_NoSeries_Description {
            get {
                return ResourceManager.GetString("HomePage.NoSeries.Description", resourceCulture);
            }
        }
        
        public static string HomePage_AddFirstSeries {
            get {
                return ResourceManager.GetString("HomePage.AddFirstSeries", resourceCulture);
            }
        }
        
        public static string HomePage_RecentSeries {
            get {
                return ResourceManager.GetString("HomePage.RecentSeries", resourceCulture);
            }
        }
        
        public static string HomePage_SeriesCount {
            get {
                return ResourceManager.GetString("HomePage.SeriesCount", resourceCulture);
            }
        }
        
        public static string HomePage_SelectFolder {
            get {
                return ResourceManager.GetString("HomePage.SelectFolder", resourceCulture);
            }
        }
        
        public static string HomePage_UploadSuccess {
            get {
                return ResourceManager.GetString("HomePage.UploadSuccess", resourceCulture);
            }
        }
        
        public static string HomePage_UploadError {
            get {
                return ResourceManager.GetString("HomePage.UploadError", resourceCulture);
            }
        }
        
        public static string HomePage_UploadFailure {
            get {
                return ResourceManager.GetString("HomePage.UploadFailure", resourceCulture);
            }
        }
        
        public static string IssuesPage_Title {
            get {
                return ResourceManager.GetString("IssuesPage.Title", resourceCulture);
            }
        }
        
        public static string IssuesPage_Automatic {
            get {
                return ResourceManager.GetString("IssuesPage.Automatic", resourceCulture);
            }
        }
        
        public static string IssuesPage_Reported {
            get {
                return ResourceManager.GetString("IssuesPage.Reported", resourceCulture);
            }
        }
        
        public static string IssuesPage_Chapters {
            get {
                return ResourceManager.GetString("IssuesPage.Chapters", resourceCulture);
            }
        }
        
        public static string IssuesPage_Series {
            get {
                return ResourceManager.GetString("IssuesPage.Series", resourceCulture);
            }
        }
        
        public static string IssuesPage_AutomaticChapters {
            get {
                return ResourceManager.GetString("IssuesPage.AutomaticChapters", resourceCulture);
            }
        }
        
        public static string IssuesPage_AutomaticSeries {
            get {
                return ResourceManager.GetString("IssuesPage.AutomaticSeries", resourceCulture);
            }
        }
        
        public static string IssuesPage_ReportedChapters {
            get {
                return ResourceManager.GetString("IssuesPage.ReportedChapters", resourceCulture);
            }
        }
        
        public static string IssuesPage_ReportedSeries {
            get {
                return ResourceManager.GetString("IssuesPage.ReportedSeries", resourceCulture);
            }
        }
        
        public static string IssuesPage_NoAutomaticChapter {
            get {
                return ResourceManager.GetString("IssuesPage.NoAutomaticChapter", resourceCulture);
            }
        }
        
        public static string IssuesPage_NoAutomaticSeries {
            get {
                return ResourceManager.GetString("IssuesPage.NoAutomaticSeries", resourceCulture);
            }
        }
        
        public static string IssuesPage_NoReportedChapter {
            get {
                return ResourceManager.GetString("IssuesPage.NoReportedChapter", resourceCulture);
            }
        }
        
        public static string IssuesPage_NoReportedSeries {
            get {
                return ResourceManager.GetString("IssuesPage.NoReportedSeries", resourceCulture);
            }
        }
        
        public static string IssuesPage_ChapterInfo {
            get {
                return ResourceManager.GetString("IssuesPage.ChapterInfo", resourceCulture);
            }
        }
        
        public static string IssuesPage_SeriesInfo {
            get {
                return ResourceManager.GetString("IssuesPage.SeriesInfo", resourceCulture);
            }
        }
        
        public static string IssuesPage_ChapterUserInfo {
            get {
                return ResourceManager.GetString("IssuesPage.ChapterUserInfo", resourceCulture);
            }
        }
        
        public static string IssuesPage_SeriesUserInfo {
            get {
                return ResourceManager.GetString("IssuesPage.SeriesUserInfo", resourceCulture);
            }
        }
        
        public static string IssuesPage_ReplacementSuccessful {
            get {
                return ResourceManager.GetString("IssuesPage.ReplacementSuccessful", resourceCulture);
            }
        }
        
        public static string IssuesPage_ReplacementFailed {
            get {
                return ResourceManager.GetString("IssuesPage.ReplacementFailed", resourceCulture);
            }
        }
        
        public static string LibraryPage_SeriesCount {
            get {
                return ResourceManager.GetString("LibraryPage.SeriesCount", resourceCulture);
            }
        }
        
        public static string LibraryPage_Delete {
            get {
                return ResourceManager.GetString("LibraryPage.Delete", resourceCulture);
            }
        }
        
        public static string LibraryPage_EmptyLibrary_Title {
            get {
                return ResourceManager.GetString("LibraryPage.EmptyLibrary.Title", resourceCulture);
            }
        }
        
        public static string LibraryPage_EmptyLibrary_Description {
            get {
                return ResourceManager.GetString("LibraryPage.EmptyLibrary.Description", resourceCulture);
            }
        }
        
        public static string LibraryPage_LibrarySeries_Title {
            get {
                return ResourceManager.GetString("LibraryPage.LibrarySeries.Title", resourceCulture);
            }
        }
        
        public static string RankPage_Title {
            get {
                return ResourceManager.GetString("RankPage.Title", resourceCulture);
            }
        }
        
        public static string RankPage_RanksCount {
            get {
                return ResourceManager.GetString("RankPage.RanksCount", resourceCulture);
            }
        }
        
        public static string RankPage_NewRank {
            get {
                return ResourceManager.GetString("RankPage.NewRank", resourceCulture);
            }
        }
        
        public static string RankPage_NoRanks_Title {
            get {
                return ResourceManager.GetString("RankPage.NoRanks.Title", resourceCulture);
            }
        }
        
        public static string RankPage_NoRanks_Description {
            get {
                return ResourceManager.GetString("RankPage.NoRanks.Description", resourceCulture);
            }
        }
        
        public static string RankPage_CreateFirstRank {
            get {
                return ResourceManager.GetString("RankPage.CreateFirstRank", resourceCulture);
            }
        }
        
        public static string RankPage_RanksList_Title {
            get {
                return ResourceManager.GetString("RankPage.RanksList.Title", resourceCulture);
            }
        }
        
        public static string RankPage_Level {
            get {
                return ResourceManager.GetString("RankPage.Level", resourceCulture);
            }
        }
        
        public static string PersonPage_Title {
            get {
                return ResourceManager.GetString("PersonPage.Title", resourceCulture);
            }
        }
        
        public static string PersonPage_PersonsCount {
            get {
                return ResourceManager.GetString("PersonPage.PersonsCount", resourceCulture);
            }
        }
        
        public static string PersonPage_NewPerson {
            get {
                return ResourceManager.GetString("PersonPage.NewPerson", resourceCulture);
            }
        }
        
        public static string PersonPage_NoPersons_Title {
            get {
                return ResourceManager.GetString("PersonPage.NoPersons.Title", resourceCulture);
            }
        }
        
        public static string PersonPage_NoPersons_Description {
            get {
                return ResourceManager.GetString("PersonPage.NoPersons.Description", resourceCulture);
            }
        }
        
        public static string PersonPage_CreateFirstPerson {
            get {
                return ResourceManager.GetString("PersonPage.CreateFirstPerson", resourceCulture);
            }
        }
        
        public static string PersonPage_PersonsList_Title {
            get {
                return ResourceManager.GetString("PersonPage.PersonsList.Title", resourceCulture);
            }
        }
        
        public static string SeriePage_ChangeButton {
            get {
                return ResourceManager.GetString("SeriePage.ChangeButton", resourceCulture);
            }
        }
        
        public static string SeriePage_SerieRating {
            get {
                return ResourceManager.GetString("SeriePage.SerieRating", resourceCulture);
            }
        }
        
        public static string SeriePage_Chapters {
            get {
                return ResourceManager.GetString("SeriePage.Chapters", resourceCulture);
            }
        }
        
        public static string SeriePage_NoChaptersAvailable {
            get {
                return ResourceManager.GetString("SeriePage.NoChaptersAvailable", resourceCulture);
            }
        }
        
        public static string SeriePage_NoChaptersDescription {
            get {
                return ResourceManager.GetString("SeriePage.NoChaptersDescription", resourceCulture);
            }
        }
        
        public static string SeriePage_ChapterCount {
            get {
                return ResourceManager.GetString("SeriePage.ChapterCount", resourceCulture);
            }
        }
        
        public static string SeriePage_SelectPosterImage {
            get {
                return ResourceManager.GetString("SeriePage.SelectPosterImage", resourceCulture);
            }
        }
        
        public static string SeriePage_PosterReplacedSuccess {
            get {
                return ResourceManager.GetString("SeriePage.PosterReplacedSuccess", resourceCulture);
            }
        }
        
        public static string SeriePage_ErrorReplacingPoster {
            get {
                return ResourceManager.GetString("SeriePage.ErrorReplacingPoster", resourceCulture);
            }
        }
        
        public static string SeriePage_ErrorUpdatingSerie {
            get {
                return ResourceManager.GetString("SeriePage.ErrorUpdatingSerie", resourceCulture);
            }
        }
        
        public static string SeriePage_RankSetCorrectly {
            get {
                return ResourceManager.GetString("SeriePage.RankSetCorrectly", resourceCulture);
            }
        }
        
        public static string SeriePage_Tags {
            get {
                return ResourceManager.GetString("SeriePage.Tags", resourceCulture);
            }
        }
        
        public static string SeriePage_Persons {
            get {
                return ResourceManager.GetString("SeriePage.Persons", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_Title {
            get {
                return ResourceManager.GetString("SettingsAppPage.Title", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_Subtitle {
            get {
                return ResourceManager.GetString("SettingsAppPage.Subtitle", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_DisplayMode {
            get {
                return ResourceManager.GetString("SettingsAppPage.DisplayMode", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_DarkMode {
            get {
                return ResourceManager.GetString("SettingsAppPage.DarkMode", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_ColorTheme {
            get {
                return ResourceManager.GetString("SettingsAppPage.ColorTheme", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_SelectedTheme {
            get {
                return ResourceManager.GetString("SettingsAppPage.SelectedTheme", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_ColorPreview {
            get {
                return ResourceManager.GetString("SettingsAppPage.ColorPreview", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_PrimaryColor {
            get {
                return ResourceManager.GetString("SettingsAppPage.PrimaryColor", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_SecondaryColor {
            get {
                return ResourceManager.GetString("SettingsAppPage.SecondaryColor", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_TertiaryColor {
            get {
                return ResourceManager.GetString("SettingsAppPage.TertiaryColor", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_Language {
            get {
                return ResourceManager.GetString("SettingsAppPage.Language", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_SelectedLanguage {
            get {
                return ResourceManager.GetString("SettingsAppPage.SelectedLanguage", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_Title {
            get {
                return ResourceManager.GetString("SettingsServerPage.Title", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_Subtitle {
            get {
                return ResourceManager.GetString("SettingsServerPage.Subtitle", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_AddSavePoint {
            get {
                return ResourceManager.GetString("SettingsServerPage.AddSavePoint", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_AddLibrary {
            get {
                return ResourceManager.GetString("SettingsServerPage.AddLibrary", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_PosterConfig {
            get {
                return ResourceManager.GetString("SettingsServerPage.PosterConfig", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_PosterName {
            get {
                return ResourceManager.GetString("SettingsServerPage.PosterName", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_BannerConfig {
            get {
                return ResourceManager.GetString("SettingsServerPage.BannerConfig", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_BannerName {
            get {
                return ResourceManager.GetString("SettingsServerPage.BannerName", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_ImageFormat {
            get {
                return ResourceManager.GetString("SettingsServerPage.ImageFormat", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_Quality {
            get {
                return ResourceManager.GetString("SettingsServerPage.Quality", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MaxWidth {
            get {
                return ResourceManager.GetString("SettingsServerPage.MaxWidth", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MinWidth {
            get {
                return ResourceManager.GetString("SettingsServerPage.MinWidth", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_ChapterConfig {
            get {
                return ResourceManager.GetString("SettingsServerPage.ChapterConfig", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MaxPageWidth {
            get {
                return ResourceManager.GetString("SettingsServerPage.MaxPageWidth", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MinPageWidth {
            get {
                return ResourceManager.GetString("SettingsServerPage.MinPageWidth", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_ArchiveFormat {
            get {
                return ResourceManager.GetString("SettingsServerPage.ArchiveFormat", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_SeriesConfig {
            get {
                return ResourceManager.GetString("SettingsServerPage.SeriesConfig", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MaxDescriptionLength {
            get {
                return ResourceManager.GetString("SettingsServerPage.MaxDescriptionLength", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MinDescriptionLength {
            get {
                return ResourceManager.GetString("SettingsServerPage.MinDescriptionLength", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_TipTitle {
            get {
                return ResourceManager.GetString("SettingsServerPage.TipTitle", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_TipMessage {
            get {
                return ResourceManager.GetString("SettingsServerPage.TipMessage", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_SaveButton {
            get {
                return ResourceManager.GetString("SettingsServerPage.SaveButton", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_SettingsUpdatedSuccess {
            get {
                return ResourceManager.GetString("SettingsServerPage.SettingsUpdatedSuccess", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_ErrorCreatingSavePoint {
            get {
                return ResourceManager.GetString("SettingsServerPage.ErrorCreatingSavePoint", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_ErrorCreatingLibrary {
            get {
                return ResourceManager.GetString("SettingsServerPage.ErrorCreatingLibrary", resourceCulture);
            }
        }
        
        public static string SettingsFeaturesPage_Title {
            get {
                return ResourceManager.GetString("SettingsFeaturesPage.Title", resourceCulture);
            }
        }
        
        public static string SettingsFeaturesPage_Subtitle {
            get {
                return ResourceManager.GetString("SettingsFeaturesPage.Subtitle", resourceCulture);
            }
        }
        
        public static string SettingsFeaturesPage_Save {
            get {
                return ResourceManager.GetString("SettingsFeaturesPage.Save", resourceCulture);
            }
        }
        
        public static string SettingsFeaturesPage_FeaturesUpdatedSuccess {
            get {
                return ResourceManager.GetString("SettingsFeaturesPage.FeaturesUpdatedSuccess", resourceCulture);
            }
        }
        
        public static string SettingsFeaturesPage_Feature_Ranks {
            get {
                return ResourceManager.GetString("SettingsFeaturesPage.Feature.Ranks", resourceCulture);
            }
        }
        
        public static string SettingsFeaturesPage_Feature_AutomaticIssues {
            get {
                return ResourceManager.GetString("SettingsFeaturesPage.Feature.AutomaticIssues", resourceCulture);
            }
        }
        
        public static string SettingsFeaturesPage_Feature_ReportedIssues {
            get {
                return ResourceManager.GetString("SettingsFeaturesPage.Feature.ReportedIssues", resourceCulture);
            }
        }
        
        public static string SettingsFeaturesPage_Description_Ranks {
            get {
                return ResourceManager.GetString("SettingsFeaturesPage.Description.Ranks", resourceCulture);
            }
        }
        
        public static string SettingsFeaturesPage_Description_AutomaticIssues {
            get {
                return ResourceManager.GetString("SettingsFeaturesPage.Description.AutomaticIssues", resourceCulture);
            }
        }
        
        public static string SettingsFeaturesPage_Description_ReportedIssues {
            get {
                return ResourceManager.GetString("SettingsFeaturesPage.Description.ReportedIssues", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Subtitle {
            get {
                return ResourceManager.GetString("ServerStatsPage.Subtitle", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_DiskUsage_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.DiskUsage.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_DiskUsage_Used {
            get {
                return ResourceManager.GetString("ServerStatsPage.DiskUsage.Used", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_DiskUsage_Available {
            get {
                return ResourceManager.GetString("ServerStatsPage.DiskUsage.Available", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_UserActivity_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.UserActivity.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_UserActivity_Active {
            get {
                return ResourceManager.GetString("ServerStatsPage.UserActivity.Active", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_UserActivity_Inactive {
            get {
                return ResourceManager.GetString("ServerStatsPage.UserActivity.Inactive", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Content_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.Content.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Content_Series {
            get {
                return ResourceManager.GetString("ServerStatsPage.Content.Series", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Content_Chapters {
            get {
                return ResourceManager.GetString("ServerStatsPage.Content.Chapters", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_LibraryDistribution_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.LibraryDistribution.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_NeverRead_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.NeverRead.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Charts_Used {
            get {
                return ResourceManager.GetString("ServerStatsPage.Charts.Used", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Charts_Available {
            get {
                return ResourceManager.GetString("ServerStatsPage.Charts.Available", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Charts_Active {
            get {
                return ResourceManager.GetString("ServerStatsPage.Charts.Active", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Charts_Inactive {
            get {
                return ResourceManager.GetString("ServerStatsPage.Charts.Inactive", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Title {
            get {
                return ResourceManager.GetString("UserStatsPage.Title", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Subtitle {
            get {
                return ResourceManager.GetString("UserStatsPage.Subtitle", resourceCulture);
            }
        }
        
        public static string UserStatsPage_SeriesProgress_Title {
            get {
                return ResourceManager.GetString("UserStatsPage.SeriesProgress.Title", resourceCulture);
            }
        }
        
        public static string UserStatsPage_SeriesProgress_Completed {
            get {
                return ResourceManager.GetString("UserStatsPage.SeriesProgress.Completed", resourceCulture);
            }
        }
        
        public static string UserStatsPage_SeriesProgress_InProgress {
            get {
                return ResourceManager.GetString("UserStatsPage.SeriesProgress.InProgress", resourceCulture);
            }
        }
        
        public static string UserStatsPage_SeriesProgress_Remaining {
            get {
                return ResourceManager.GetString("UserStatsPage.SeriesProgress.Remaining", resourceCulture);
            }
        }
        
        public static string UserStatsPage_ChaptersProgress_Title {
            get {
                return ResourceManager.GetString("UserStatsPage.ChaptersProgress.Title", resourceCulture);
            }
        }
        
        public static string UserStatsPage_ChaptersProgress_Read {
            get {
                return ResourceManager.GetString("UserStatsPage.ChaptersProgress.Read", resourceCulture);
            }
        }
        
        public static string UserStatsPage_ChaptersProgress_Remaining {
            get {
                return ResourceManager.GetString("UserStatsPage.ChaptersProgress.Remaining", resourceCulture);
            }
        }
        
        public static string UserStatsPage_RankDistribution_Title {
            get {
                return ResourceManager.GetString("UserStatsPage.RankDistribution.Title", resourceCulture);
            }
        }
        
        public static string UserStatsPage_ReadsPerDay_Title {
            get {
                return ResourceManager.GetString("UserStatsPage.ReadsPerDay.Title", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_Completed {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.Completed", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_InProgress {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.InProgress", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_Remaining {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.Remaining", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_Read {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.Read", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_RemainingChapters {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.RemainingChapters", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_SeriesCount {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.SeriesCount", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_DailyReads {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.DailyReads", resourceCulture);
            }
        }
        
        public static string TagPage_Management {
            get {
                return ResourceManager.GetString("TagPage.Management", resourceCulture);
            }
        }
        
        public static string TagPage_Count {
            get {
                return ResourceManager.GetString("TagPage.Count", resourceCulture);
            }
        }
        
        public static string TagPage_NewTag {
            get {
                return ResourceManager.GetString("TagPage.NewTag", resourceCulture);
            }
        }
        
        public static string TagPage_NoTags {
            get {
                return ResourceManager.GetString("TagPage.NoTags", resourceCulture);
            }
        }
        
        public static string TagPage_NoTags_Description {
            get {
                return ResourceManager.GetString("TagPage.NoTags.Description", resourceCulture);
            }
        }
        
        public static string TagPage_CreateFirst {
            get {
                return ResourceManager.GetString("TagPage.CreateFirst", resourceCulture);
            }
        }
        
        public static string TagPage_List {
            get {
                return ResourceManager.GetString("TagPage.List", resourceCulture);
            }
        }
        
        public static string TagPage_DefaultName {
            get {
                return ResourceManager.GetString("TagPage.DefaultName", resourceCulture);
            }
        }
        
        public static string TagPage_CreateError {
            get {
                return ResourceManager.GetString("TagPage.CreateError", resourceCulture);
            }
        }
        
        public static string TagPage_UpdateError {
            get {
                return ResourceManager.GetString("TagPage.UpdateError", resourceCulture);
            }
        }
        
        public static string TagPage_DeleteError {
            get {
                return ResourceManager.GetString("TagPage.DeleteError", resourceCulture);
            }
        }
        
        public static string UserPage_Management {
            get {
                return ResourceManager.GetString("UserPage.Management", resourceCulture);
            }
        }
        
        public static string UserPage_Count {
            get {
                return ResourceManager.GetString("UserPage.Count", resourceCulture);
            }
        }
        
        public static string UserPage_Add {
            get {
                return ResourceManager.GetString("UserPage.Add", resourceCulture);
            }
        }
        
        public static string UserPage_NoUsers {
            get {
                return ResourceManager.GetString("UserPage.NoUsers", resourceCulture);
            }
        }
        
        public static string UserPage_NoUsers_Description {
            get {
                return ResourceManager.GetString("UserPage.NoUsers.Description", resourceCulture);
            }
        }
        
        public static string UserPage_CreateFirst {
            get {
                return ResourceManager.GetString("UserPage.CreateFirst", resourceCulture);
            }
        }
        
        public static string UserPage_List {
            get {
                return ResourceManager.GetString("UserPage.List", resourceCulture);
            }
        }
        
        public static string UserPage_Permissions {
            get {
                return ResourceManager.GetString("UserPage.Permissions", resourceCulture);
            }
        }
        
        public static string UserPage_CreateError {
            get {
                return ResourceManager.GetString("UserPage.CreateError", resourceCulture);
            }
        }
        
        public static string UserPage_DeleteError {
            get {
                return ResourceManager.GetString("UserPage.DeleteError", resourceCulture);
            }
        }
        
        public static string UserPage_UpdatePermissionsError {
            get {
                return ResourceManager.GetString("UserPage.UpdatePermissionsError", resourceCulture);
            }
        }
        
        public static string LibraryCreatePopup_NewLibrary {
            get {
                return ResourceManager.GetString("LibraryCreatePopup.NewLibrary", resourceCulture);
            }
        }
        
        public static string LibraryCreatePopup_Description {
            get {
                return ResourceManager.GetString("LibraryCreatePopup.Description", resourceCulture);
            }
        }
        
        public static string LibraryCreatePopup_Name {
            get {
                return ResourceManager.GetString("LibraryCreatePopup.Name", resourceCulture);
            }
        }
        
        public static string LibraryCreatePopup_Name_Placeholder {
            get {
                return ResourceManager.GetString("LibraryCreatePopup.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string LibraryCreatePopup_Info {
            get {
                return ResourceManager.GetString("LibraryCreatePopup.Info", resourceCulture);
            }
        }
        
        public static string RankEditPopup_Title {
            get {
                return ResourceManager.GetString("RankEditPopup.Title", resourceCulture);
            }
        }
        
        public static string RankEditPopup_Description {
            get {
                return ResourceManager.GetString("RankEditPopup.Description", resourceCulture);
            }
        }
        
        public static string RankEditPopup_Name {
            get {
                return ResourceManager.GetString("RankEditPopup.Name", resourceCulture);
            }
        }
        
        public static string RankEditPopup_Name_Placeholder {
            get {
                return ResourceManager.GetString("RankEditPopup.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string RankEditPopup_Value {
            get {
                return ResourceManager.GetString("RankEditPopup.Value", resourceCulture);
            }
        }
        
        public static string PersonEditPopup_Title {
            get {
                return ResourceManager.GetString("PersonEditPopup.Title", resourceCulture);
            }
        }
        
        public static string PersonEditPopup_Description {
            get {
                return ResourceManager.GetString("PersonEditPopup.Description", resourceCulture);
            }
        }
        
        public static string PersonEditPopup_FirstName {
            get {
                return ResourceManager.GetString("PersonEditPopup.FirstName", resourceCulture);
            }
        }
        
        public static string PersonEditPopup_FirstName_Placeholder {
            get {
                return ResourceManager.GetString("PersonEditPopup.FirstName.Placeholder", resourceCulture);
            }
        }
        
        public static string PersonEditPopup_LastName {
            get {
                return ResourceManager.GetString("PersonEditPopup.LastName", resourceCulture);
            }
        }
        
        public static string PersonEditPopup_LastName_Placeholder {
            get {
                return ResourceManager.GetString("PersonEditPopup.LastName.Placeholder", resourceCulture);
            }
        }
        
        public static string PersonEditPopup_Pseudonym {
            get {
                return ResourceManager.GetString("PersonEditPopup.Pseudonym", resourceCulture);
            }
        }
        
        public static string PersonEditPopup_Pseudonym_Placeholder {
            get {
                return ResourceManager.GetString("PersonEditPopup.Pseudonym.Placeholder", resourceCulture);
            }
        }
        
        public static string PersonEditPopup_Role {
            get {
                return ResourceManager.GetString("PersonEditPopup.Role", resourceCulture);
            }
        }
        
        public static string SavePointCreatePopup_Title {
            get {
                return ResourceManager.GetString("SavePointCreatePopup.Title", resourceCulture);
            }
        }
        
        public static string SavePointCreatePopup_Description {
            get {
                return ResourceManager.GetString("SavePointCreatePopup.Description", resourceCulture);
            }
        }
        
        public static string SavePointCreatePopup_Path {
            get {
                return ResourceManager.GetString("SavePointCreatePopup.Path", resourceCulture);
            }
        }
        
        public static string SavePointCreatePopup_Path_Placeholder {
            get {
                return ResourceManager.GetString("SavePointCreatePopup.Path.Placeholder", resourceCulture);
            }
        }
        
        public static string SavePointCreatePopup_Tip {
            get {
                return ResourceManager.GetString("SavePointCreatePopup.Tip", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Serie_Title {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Serie.Title", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Serie_Description {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Serie.Description", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Serie_Title_Placeholder {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Serie.Title.Placeholder", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Serie_Description_Placeholder {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Serie.Description.Placeholder", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Status {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Status", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Library {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Library", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Tags {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Tags", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Tags_Placeholder {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Tags.Placeholder", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_NoTags {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.NoTags", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Persons {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Persons", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Persons_Placeholder {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Persons.Placeholder", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_NoPersons {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.NoPersons", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Title {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Title", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Description {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Description", resourceCulture);
            }
        }
        
        public static string TagEditPopup_Title {
            get {
                return ResourceManager.GetString("TagEditPopup.Title", resourceCulture);
            }
        }
        
        public static string TagEditPopup_Description {
            get {
                return ResourceManager.GetString("TagEditPopup.Description", resourceCulture);
            }
        }
        
        public static string TagEditPopup_Name {
            get {
                return ResourceManager.GetString("TagEditPopup.Name", resourceCulture);
            }
        }
        
        public static string TagEditPopup_Name_Placeholder {
            get {
                return ResourceManager.GetString("TagEditPopup.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string TagEditPopup_Color {
            get {
                return ResourceManager.GetString("TagEditPopup.Color", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Title {
            get {
                return ResourceManager.GetString("UserCreatePopup.Title", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Description {
            get {
                return ResourceManager.GetString("UserCreatePopup.Description", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Username {
            get {
                return ResourceManager.GetString("UserCreatePopup.Username", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Username_Placeholder {
            get {
                return ResourceManager.GetString("UserCreatePopup.Username.Placeholder", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Password {
            get {
                return ResourceManager.GetString("UserCreatePopup.Password", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Password_Placeholder {
            get {
                return ResourceManager.GetString("UserCreatePopup.Password.Placeholder", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Role {
            get {
                return ResourceManager.GetString("UserCreatePopup.Role", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Tip {
            get {
                return ResourceManager.GetString("UserCreatePopup.Tip", resourceCulture);
            }
        }
        
        public static string ConfirmCancelPopup_Confirm {
            get {
                return ResourceManager.GetString("ConfirmCancelPopup.Confirm", resourceCulture);
            }
        }
        
        public static string ConfirmCancelPopup_Cancel {
            get {
                return ResourceManager.GetString("ConfirmCancelPopup.Cancel", resourceCulture);
            }
        }
        
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow.Title", resourceCulture);
            }
        }
        
        public static string MainWindow_Home {
            get {
                return ResourceManager.GetString("MainWindow.Home", resourceCulture);
            }
        }
        
        public static string MainWindow_Libraries {
            get {
                return ResourceManager.GetString("MainWindow.Libraries", resourceCulture);
            }
        }
        
        public static string MainWindow_Admin {
            get {
                return ResourceManager.GetString("MainWindow.Admin", resourceCulture);
            }
        }
        
        public static string MainWindow_Issues {
            get {
                return ResourceManager.GetString("MainWindow.Issues", resourceCulture);
            }
        }
        
        public static string MainWindow_Users {
            get {
                return ResourceManager.GetString("MainWindow.Users", resourceCulture);
            }
        }
        
        public static string MainWindow_Ranks {
            get {
                return ResourceManager.GetString("MainWindow.Ranks", resourceCulture);
            }
        }
        
        public static string MainWindow_Tags {
            get {
                return ResourceManager.GetString("MainWindow.Tags", resourceCulture);
            }
        }
        
        public static string MainWindow_Parameters {
            get {
                return ResourceManager.GetString("MainWindow.Parameters", resourceCulture);
            }
        }
        
        public static string MainWindow_Stats {
            get {
                return ResourceManager.GetString("MainWindow.Stats", resourceCulture);
            }
        }
        
        public static string MainWindow_Stats_User {
            get {
                return ResourceManager.GetString("MainWindow.Stats.User", resourceCulture);
            }
        }
        
        public static string MainWindow_Stats_Server {
            get {
                return ResourceManager.GetString("MainWindow.Stats.Server", resourceCulture);
            }
        }
        
        public static string MainWindow_Parameters_UI {
            get {
                return ResourceManager.GetString("MainWindow.Parameters.UI", resourceCulture);
            }
        }
        
        public static string MainWindow_Parameters_Features {
            get {
                return ResourceManager.GetString("MainWindow.Parameters.Features", resourceCulture);
            }
        }
        
        public static string MainWindow_Logout {
            get {
                return ResourceManager.GetString("MainWindow.Logout", resourceCulture);
            }
        }
        
        public static string MainWindow_RunningTasks {
            get {
                return ResourceManager.GetString("MainWindow.RunningTasks", resourceCulture);
            }
        }
        
        public static string MainWindow_Parameters_Server {
            get {
                return ResourceManager.GetString("MainWindow.Parameters.Server", resourceCulture);
            }
        }
        
        public static string CreateChapterIssuePopup_Title {
            get {
                return ResourceManager.GetString("CreateChapterIssuePopup.Title", resourceCulture);
            }
        }
        
        public static string CreateChapterIssuePopup_Description {
            get {
                return ResourceManager.GetString("CreateChapterIssuePopup.Description", resourceCulture);
            }
        }
        
        public static string CreateChapterIssuePopup_Type {
            get {
                return ResourceManager.GetString("CreateChapterIssuePopup.Type", resourceCulture);
            }
        }
        
        public static string CreateChapterIssuePopup_Tip {
            get {
                return ResourceManager.GetString("CreateChapterIssuePopup.Tip", resourceCulture);
            }
        }
        
        public static string LoginPage_Invalid_Host_Port {
            get {
                return ResourceManager.GetString("LoginPage.Invalid.Host.Port", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_NoFolderSelected {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.NoFolderSelected", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_Information {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.Information", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_Information_Text1 {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.Information.Text1", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_Information_Text2 {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.Information.Text2", resourceCulture);
            }
        }
        
        public static string AutoCleanupPage_Title {
            get {
                return ResourceManager.GetString("AutoCleanupPage.Title", resourceCulture);
            }
        }
        
        public static string AutoCleanupPage_Subtitle {
            get {
                return ResourceManager.GetString("AutoCleanupPage.Subtitle", resourceCulture);
            }
        }
        
        public static string AutoCleanupPage_ArchiveProcessing {
            get {
                return ResourceManager.GetString("AutoCleanupPage.ArchiveProcessing", resourceCulture);
            }
        }
        
        public static string AutoCleanupPage_ImageProcessing {
            get {
                return ResourceManager.GetString("AutoCleanupPage.ImageProcessing", resourceCulture);
            }
        }
        
        public static string AutoCleanupPage_StartCleanup {
            get {
                return ResourceManager.GetString("AutoCleanupPage.StartCleanup", resourceCulture);
            }
        }
        
        public static string AutoCleanupPage_Processing {
            get {
                return ResourceManager.GetString("AutoCleanupPage.Processing", resourceCulture);
            }
        }
        
        public static string AutoCleanupPage_Errors {
            get {
                return ResourceManager.GetString("AutoCleanupPage.Errors", resourceCulture);
            }
        }
        
        public static string ManualCleanupPage_SerieFolders {
            get {
                return ResourceManager.GetString("ManualCleanupPage.SerieFolders", resourceCulture);
            }
        }
        
        public static string ManualCleanupPage_Images {
            get {
                return ResourceManager.GetString("ManualCleanupPage.Images", resourceCulture);
            }
        }
        
        public static string ManualCleanupPage_ToEdit {
            get {
                return ResourceManager.GetString("ManualCleanupPage.ToEdit", resourceCulture);
            }
        }
        
        public static string ManualCleanupPage_EditSelected {
            get {
                return ResourceManager.GetString("ManualCleanupPage.EditSelected", resourceCulture);
            }
        }
        
        public static string ManualCleanupPage_RestoreLastImage {
            get {
                return ResourceManager.GetString("ManualCleanupPage.RestoreLastImage", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_Next {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.Next", resourceCulture);
            }
        }
        
        public static string ManualCleanupPage_Next {
            get {
                return ResourceManager.GetString("ManualCleanupPage.Next", resourceCulture);
            }
        }
        
        public static string RolePage_Title {
            get {
                return ResourceManager.GetString("RolePage.Title", resourceCulture);
            }
        }
        
        public static string RolePage_RolesCount {
            get {
                return ResourceManager.GetString("RolePage.RolesCount", resourceCulture);
            }
        }
        
        public static string RolePage_NewRole {
            get {
                return ResourceManager.GetString("RolePage.NewRole", resourceCulture);
            }
        }
        
        public static string RolePage_NoRoles_Title {
            get {
                return ResourceManager.GetString("RolePage.NoRoles.Title", resourceCulture);
            }
        }
        
        public static string RolePage_NoRoles_Description {
            get {
                return ResourceManager.GetString("RolePage.NoRoles.Description", resourceCulture);
            }
        }
        
        public static string RolePage_CreateFirstRole {
            get {
                return ResourceManager.GetString("RolePage.CreateFirstRole", resourceCulture);
            }
        }
        
        public static string RolePage_RolesList_Title {
            get {
                return ResourceManager.GetString("RolePage.RolesList.Title", resourceCulture);
            }
        }
        
        public static string RoleEditPopup_Title {
            get {
                return ResourceManager.GetString("RoleEditPopup.Title", resourceCulture);
            }
        }
        
        public static string RoleEditPopup_Description {
            get {
                return ResourceManager.GetString("RoleEditPopup.Description", resourceCulture);
            }
        }
        
        public static string RoleEditPopup_Name {
            get {
                return ResourceManager.GetString("RoleEditPopup.Name", resourceCulture);
            }
        }
        
        public static string RoleEditPopup_Name_Placeholder {
            get {
                return ResourceManager.GetString("RoleEditPopup.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Title {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Title", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Sources {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Sources", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_AddSource {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.AddSource", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_FetchAll {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.FetchAll", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_ClearAll {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.ClearAll", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_ProgressOverview {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.ProgressOverview", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_OverallProgress {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.OverallProgress", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_TotalSources {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.TotalSources", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Completed {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Completed", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_InProgress {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.InProgress", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_SourceDetails {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.SourceDetails", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Active {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Active", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_FilesProcessed {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.FilesProcessed", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Progress {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Progress", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_ProcessingFolder {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.ProcessingFolder", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_DestinationPath {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.DestinationPath", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_DestinationPath_Placeholder {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.DestinationPath.Placeholder", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Browse {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Browse", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_FolderInformation {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.FolderInformation", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Status {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Status", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Status_Ready {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Status.Ready", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Files {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Files", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Size {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Size", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Tip {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Tip", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_OpenFolder {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.OpenFolder", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_ClearFolder {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.ClearFolder", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_SelectSourceFolder {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.SelectSourceFolder", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_SelectProcessingFolder {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.SelectProcessingFolder", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_FilesFormat {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.FilesFormat", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_Title {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.Title", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_SourceFolders {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.SourceFolders", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_SourceFolders_Description {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.SourceFolders.Description", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_AddSource {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.AddSource", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_RemoveSource {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.RemoveSource", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_NoSources {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.NoSources", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_ProcessingFolder {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.ProcessingFolder", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_ProcessingFolder_Description {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.ProcessingFolder.Description", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_Browse {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.Browse", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_OpenFolder {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.OpenFolder", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_CurrentPath {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.CurrentPath", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_SelectFolder {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.SelectFolder", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_Settings {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.Settings", resourceCulture);
            }
        }
        
        public static string ConfigureUploadPage_SaveSettings {
            get {
                return ResourceManager.GetString("ConfigureUploadPage.SaveSettings", resourceCulture);
            }
        }
        
        public static string MainWindow_Upload {
            get {
                return ResourceManager.GetString("MainWindow.Upload", resourceCulture);
            }
        }
        
        public static string FetchFromSourcePage_Skip {
            get {
                return ResourceManager.GetString("FetchFromSourcePage.Skip", resourceCulture);
            }
        }
        
        public static string AutoCleanupPage_Skip {
            get {
                return ResourceManager.GetString("AutoCleanupPage.Skip", resourceCulture);
            }
        }
        
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        public static string LoginPage_Connected {
            get {
                return ResourceManager.GetString("LoginPage.Connected", resourceCulture);
            }
        }
        
        public static string ChapterPreview_ReportFailed {
            get {
                return ResourceManager.GetString("ChapterPreview.ReportFailed", resourceCulture);
            }
        }
        
        public static string Chapter_LoadPageFailed {
            get {
                return ResourceManager.GetString("Chapter.LoadPageFailed", resourceCulture);
            }
        }
        
        public static string Choice_SignalIssue {
            get {
                return ResourceManager.GetString("Choice.SignalIssue", resourceCulture);
            }
        }
        
        public static string MainWindow_Persons {
            get {
                return ResourceManager.GetString("MainWindow.Persons", resourceCulture);
            }
        }
    }
}
