//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace ManaxClient.Localization {
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (Equals(null, resourceMan)) {
                    ResourceManager temp = new ResourceManager("ManaxClient.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage.Title", resourceCulture);
            }
        }
        
        public static string LoginPage_Subtitle {
            get {
                return ResourceManager.GetString("LoginPage.Subtitle", resourceCulture);
            }
        }
        
        public static string LoginPage_Username {
            get {
                return ResourceManager.GetString("LoginPage.Username", resourceCulture);
            }
        }
        
        public static string LoginPage_Username_Placeholder {
            get {
                return ResourceManager.GetString("LoginPage.Username.Placeholder", resourceCulture);
            }
        }
        
        public static string LoginPage_Password {
            get {
                return ResourceManager.GetString("LoginPage.Password", resourceCulture);
            }
        }
        
        public static string LoginPage_Password_Placeholder {
            get {
                return ResourceManager.GetString("LoginPage.Password.Placeholder", resourceCulture);
            }
        }
        
        public static string LoginPage_Server {
            get {
                return ResourceManager.GetString("LoginPage.Server", resourceCulture);
            }
        }
        
        public static string LoginPage_Server_Placeholder {
            get {
                return ResourceManager.GetString("LoginPage.Server.Placeholder", resourceCulture);
            }
        }
        
        public static string LoginPage_SignIn {
            get {
                return ResourceManager.GetString("LoginPage.SignIn", resourceCulture);
            }
        }
        
        public static string LoginPage_Tip_Title {
            get {
                return ResourceManager.GetString("LoginPage.Tip.Title", resourceCulture);
            }
        }
        
        public static string LoginPage_Tip_Message {
            get {
                return ResourceManager.GetString("LoginPage.Tip.Message", resourceCulture);
            }
        }
        
        public static string ChapterPage_Pages {
            get {
                return ResourceManager.GetString("ChapterPage.Pages", resourceCulture);
            }
        }
        
        public static string ChapterPage_Back {
            get {
                return ResourceManager.GetString("ChapterPage.Back", resourceCulture);
            }
        }
        
        public static string ChapterPage_Previous {
            get {
                return ResourceManager.GetString("ChapterPage.Previous", resourceCulture);
            }
        }
        
        public static string ChapterPage_Chapter {
            get {
                return ResourceManager.GetString("ChapterPage.Chapter", resourceCulture);
            }
        }
        
        public static string ChapterPage_Next {
            get {
                return ResourceManager.GetString("ChapterPage.Next", resourceCulture);
            }
        }
        
        public static string ChapterPage_PreviousPage {
            get {
                return ResourceManager.GetString("ChapterPage.PreviousPage", resourceCulture);
            }
        }
        
        public static string ChapterPage_NextPage {
            get {
                return ResourceManager.GetString("ChapterPage.NextPage", resourceCulture);
            }
        }
        
        public static string HomePage_Welcome {
            get {
                return ResourceManager.GetString("HomePage.Welcome", resourceCulture);
            }
        }
        
        public static string HomePage_Subtitle {
            get {
                return ResourceManager.GetString("HomePage.Subtitle", resourceCulture);
            }
        }
        
        public static string HomePage_AddSeries {
            get {
                return ResourceManager.GetString("HomePage.AddSeries", resourceCulture);
            }
        }
        
        public static string HomePage_NoSeries {
            get {
                return ResourceManager.GetString("HomePage.NoSeries", resourceCulture);
            }
        }
        
        public static string HomePage_NoSeries_Description {
            get {
                return ResourceManager.GetString("HomePage.NoSeries.Description", resourceCulture);
            }
        }
        
        public static string HomePage_AddFirstSeries {
            get {
                return ResourceManager.GetString("HomePage.AddFirstSeries", resourceCulture);
            }
        }
        
        public static string HomePage_RecentSeries {
            get {
                return ResourceManager.GetString("HomePage.RecentSeries", resourceCulture);
            }
        }
        
        public static string HomePage_SeriesCount {
            get {
                return ResourceManager.GetString("HomePage.SeriesCount", resourceCulture);
            }
        }
        
        public static string HomePage_SelectFolder {
            get {
                return ResourceManager.GetString("HomePage.SelectFolder", resourceCulture);
            }
        }
        
        public static string HomePage_UploadSuccess {
            get {
                return ResourceManager.GetString("HomePage.UploadSuccess", resourceCulture);
            }
        }
        
        public static string HomePage_UploadError {
            get {
                return ResourceManager.GetString("HomePage.UploadError", resourceCulture);
            }
        }
        
        public static string HomePage_UploadFailure {
            get {
                return ResourceManager.GetString("HomePage.UploadFailure", resourceCulture);
            }
        }
        
        public static string IssuesPage_Title {
            get {
                return ResourceManager.GetString("IssuesPage.Title", resourceCulture);
            }
        }
        
        public static string IssuesPage_Automatic {
            get {
                return ResourceManager.GetString("IssuesPage.Automatic", resourceCulture);
            }
        }
        
        public static string IssuesPage_Reported {
            get {
                return ResourceManager.GetString("IssuesPage.Reported", resourceCulture);
            }
        }
        
        public static string IssuesPage_Chapters {
            get {
                return ResourceManager.GetString("IssuesPage.Chapters", resourceCulture);
            }
        }
        
        public static string IssuesPage_Series {
            get {
                return ResourceManager.GetString("IssuesPage.Series", resourceCulture);
            }
        }
        
        public static string IssuesPage_AutomaticChapters {
            get {
                return ResourceManager.GetString("IssuesPage.AutomaticChapters", resourceCulture);
            }
        }
        
        public static string IssuesPage_AutomaticSeries {
            get {
                return ResourceManager.GetString("IssuesPage.AutomaticSeries", resourceCulture);
            }
        }
        
        public static string IssuesPage_ReportedChapters {
            get {
                return ResourceManager.GetString("IssuesPage.ReportedChapters", resourceCulture);
            }
        }
        
        public static string IssuesPage_ReportedSeries {
            get {
                return ResourceManager.GetString("IssuesPage.ReportedSeries", resourceCulture);
            }
        }
        
        public static string IssuesPage_NoAutomaticChapter {
            get {
                return ResourceManager.GetString("IssuesPage.NoAutomaticChapter", resourceCulture);
            }
        }
        
        public static string IssuesPage_NoAutomaticSeries {
            get {
                return ResourceManager.GetString("IssuesPage.NoAutomaticSeries", resourceCulture);
            }
        }
        
        public static string IssuesPage_NoReportedChapter {
            get {
                return ResourceManager.GetString("IssuesPage.NoReportedChapter", resourceCulture);
            }
        }
        
        public static string IssuesPage_NoReportedSeries {
            get {
                return ResourceManager.GetString("IssuesPage.NoReportedSeries", resourceCulture);
            }
        }
        
        public static string IssuesPage_ChapterInfo {
            get {
                return ResourceManager.GetString("IssuesPage.ChapterInfo", resourceCulture);
            }
        }
        
        public static string IssuesPage_SeriesInfo {
            get {
                return ResourceManager.GetString("IssuesPage.SeriesInfo", resourceCulture);
            }
        }
        
        public static string IssuesPage_ChapterUserInfo {
            get {
                return ResourceManager.GetString("IssuesPage.ChapterUserInfo", resourceCulture);
            }
        }
        
        public static string IssuesPage_SeriesUserInfo {
            get {
                return ResourceManager.GetString("IssuesPage.SeriesUserInfo", resourceCulture);
            }
        }
        
        public static string IssuesPage_ReplacementSuccessful {
            get {
                return ResourceManager.GetString("IssuesPage.ReplacementSuccessful", resourceCulture);
            }
        }
        
        public static string IssuesPage_ReplacementFailed {
            get {
                return ResourceManager.GetString("IssuesPage.ReplacementFailed", resourceCulture);
            }
        }
        
        public static string LibraryPage_SeriesCount {
            get {
                return ResourceManager.GetString("LibraryPage.SeriesCount", resourceCulture);
            }
        }
        
        public static string LibraryPage_Delete {
            get {
                return ResourceManager.GetString("LibraryPage.Delete", resourceCulture);
            }
        }
        
        public static string LibraryPage_EmptyLibrary_Title {
            get {
                return ResourceManager.GetString("LibraryPage.EmptyLibrary.Title", resourceCulture);
            }
        }
        
        public static string LibraryPage_EmptyLibrary_Description {
            get {
                return ResourceManager.GetString("LibraryPage.EmptyLibrary.Description", resourceCulture);
            }
        }
        
        public static string LibraryPage_LibrarySeries_Title {
            get {
                return ResourceManager.GetString("LibraryPage.LibrarySeries.Title", resourceCulture);
            }
        }
        
        public static string RankPage_Title {
            get {
                return ResourceManager.GetString("RankPage.Title", resourceCulture);
            }
        }
        
        public static string RankPage_RanksCount {
            get {
                return ResourceManager.GetString("RankPage.RanksCount", resourceCulture);
            }
        }
        
        public static string RankPage_NewRank {
            get {
                return ResourceManager.GetString("RankPage.NewRank", resourceCulture);
            }
        }
        
        public static string RankPage_NoRanks_Title {
            get {
                return ResourceManager.GetString("RankPage.NoRanks.Title", resourceCulture);
            }
        }
        
        public static string RankPage_NoRanks_Description {
            get {
                return ResourceManager.GetString("RankPage.NoRanks.Description", resourceCulture);
            }
        }
        
        public static string RankPage_CreateFirstRank {
            get {
                return ResourceManager.GetString("RankPage.CreateFirstRank", resourceCulture);
            }
        }
        
        public static string RankPage_RanksList_Title {
            get {
                return ResourceManager.GetString("RankPage.RanksList.Title", resourceCulture);
            }
        }
        
        public static string RankPage_Level {
            get {
                return ResourceManager.GetString("RankPage.Level", resourceCulture);
            }
        }
        
        public static string SeriePage_ChangeButton {
            get {
                return ResourceManager.GetString("SeriePage.ChangeButton", resourceCulture);
            }
        }
        
        public static string SeriePage_SerieRating {
            get {
                return ResourceManager.GetString("SeriePage.SerieRating", resourceCulture);
            }
        }
        
        public static string SeriePage_Chapters {
            get {
                return ResourceManager.GetString("SeriePage.Chapters", resourceCulture);
            }
        }
        
        public static string SeriePage_NoChaptersAvailable {
            get {
                return ResourceManager.GetString("SeriePage.NoChaptersAvailable", resourceCulture);
            }
        }
        
        public static string SeriePage_NoChaptersDescription {
            get {
                return ResourceManager.GetString("SeriePage.NoChaptersDescription", resourceCulture);
            }
        }
        
        public static string SeriePage_ChapterCount {
            get {
                return ResourceManager.GetString("SeriePage.ChapterCount", resourceCulture);
            }
        }
        
        public static string SeriePage_SelectPosterImage {
            get {
                return ResourceManager.GetString("SeriePage.SelectPosterImage", resourceCulture);
            }
        }
        
        public static string SeriePage_PosterReplacedSuccess {
            get {
                return ResourceManager.GetString("SeriePage.PosterReplacedSuccess", resourceCulture);
            }
        }
        
        public static string SeriePage_ErrorReplacingPoster {
            get {
                return ResourceManager.GetString("SeriePage.ErrorReplacingPoster", resourceCulture);
            }
        }
        
        public static string SeriePage_ErrorUpdatingSerie {
            get {
                return ResourceManager.GetString("SeriePage.ErrorUpdatingSerie", resourceCulture);
            }
        }
        
        public static string SeriePage_RankSetCorrectly {
            get {
                return ResourceManager.GetString("SeriePage.RankSetCorrectly", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_Title {
            get {
                return ResourceManager.GetString("SettingsAppPage.Title", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_Subtitle {
            get {
                return ResourceManager.GetString("SettingsAppPage.Subtitle", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_DisplayMode {
            get {
                return ResourceManager.GetString("SettingsAppPage.DisplayMode", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_DarkMode {
            get {
                return ResourceManager.GetString("SettingsAppPage.DarkMode", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_ColorTheme {
            get {
                return ResourceManager.GetString("SettingsAppPage.ColorTheme", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_SelectedTheme {
            get {
                return ResourceManager.GetString("SettingsAppPage.SelectedTheme", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_ColorPreview {
            get {
                return ResourceManager.GetString("SettingsAppPage.ColorPreview", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_PrimaryColor {
            get {
                return ResourceManager.GetString("SettingsAppPage.PrimaryColor", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_SecondaryColor {
            get {
                return ResourceManager.GetString("SettingsAppPage.SecondaryColor", resourceCulture);
            }
        }
        
        public static string SettingsAppPage_TertiaryColor {
            get {
                return ResourceManager.GetString("SettingsAppPage.TertiaryColor", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_Title {
            get {
                return ResourceManager.GetString("SettingsServerPage.Title", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_Subtitle {
            get {
                return ResourceManager.GetString("SettingsServerPage.Subtitle", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_AddSavePoint {
            get {
                return ResourceManager.GetString("SettingsServerPage.AddSavePoint", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_AddLibrary {
            get {
                return ResourceManager.GetString("SettingsServerPage.AddLibrary", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_PosterConfig {
            get {
                return ResourceManager.GetString("SettingsServerPage.PosterConfig", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_PosterName {
            get {
                return ResourceManager.GetString("SettingsServerPage.PosterName", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_ImageFormat {
            get {
                return ResourceManager.GetString("SettingsServerPage.ImageFormat", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_Quality {
            get {
                return ResourceManager.GetString("SettingsServerPage.Quality", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MaxWidth {
            get {
                return ResourceManager.GetString("SettingsServerPage.MaxWidth", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MinWidth {
            get {
                return ResourceManager.GetString("SettingsServerPage.MinWidth", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_ChapterConfig {
            get {
                return ResourceManager.GetString("SettingsServerPage.ChapterConfig", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MaxPageWidth {
            get {
                return ResourceManager.GetString("SettingsServerPage.MaxPageWidth", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MinPageWidth {
            get {
                return ResourceManager.GetString("SettingsServerPage.MinPageWidth", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_ArchiveFormat {
            get {
                return ResourceManager.GetString("SettingsServerPage.ArchiveFormat", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_SeriesConfig {
            get {
                return ResourceManager.GetString("SettingsServerPage.SeriesConfig", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MaxDescriptionLength {
            get {
                return ResourceManager.GetString("SettingsServerPage.MaxDescriptionLength", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_MinDescriptionLength {
            get {
                return ResourceManager.GetString("SettingsServerPage.MinDescriptionLength", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_TipTitle {
            get {
                return ResourceManager.GetString("SettingsServerPage.TipTitle", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_TipMessage {
            get {
                return ResourceManager.GetString("SettingsServerPage.TipMessage", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_SaveButton {
            get {
                return ResourceManager.GetString("SettingsServerPage.SaveButton", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_SettingsUpdatedSuccess {
            get {
                return ResourceManager.GetString("SettingsServerPage.SettingsUpdatedSuccess", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_ErrorCreatingSavePoint {
            get {
                return ResourceManager.GetString("SettingsServerPage.ErrorCreatingSavePoint", resourceCulture);
            }
        }
        
        public static string SettingsServerPage_ErrorCreatingLibrary {
            get {
                return ResourceManager.GetString("SettingsServerPage.ErrorCreatingLibrary", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Subtitle {
            get {
                return ResourceManager.GetString("ServerStatsPage.Subtitle", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_DiskUsage_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.DiskUsage.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_DiskUsage_Used {
            get {
                return ResourceManager.GetString("ServerStatsPage.DiskUsage.Used", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_DiskUsage_Available {
            get {
                return ResourceManager.GetString("ServerStatsPage.DiskUsage.Available", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_UserActivity_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.UserActivity.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_UserActivity_Active {
            get {
                return ResourceManager.GetString("ServerStatsPage.UserActivity.Active", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_UserActivity_Inactive {
            get {
                return ResourceManager.GetString("ServerStatsPage.UserActivity.Inactive", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Content_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.Content.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Content_Series {
            get {
                return ResourceManager.GetString("ServerStatsPage.Content.Series", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Content_Chapters {
            get {
                return ResourceManager.GetString("ServerStatsPage.Content.Chapters", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_LibraryDistribution_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.LibraryDistribution.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_NeverRead_Title {
            get {
                return ResourceManager.GetString("ServerStatsPage.NeverRead.Title", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Charts_Used {
            get {
                return ResourceManager.GetString("ServerStatsPage.Charts.Used", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Charts_Available {
            get {
                return ResourceManager.GetString("ServerStatsPage.Charts.Available", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Charts_Active {
            get {
                return ResourceManager.GetString("ServerStatsPage.Charts.Active", resourceCulture);
            }
        }
        
        public static string ServerStatsPage_Charts_Inactive {
            get {
                return ResourceManager.GetString("ServerStatsPage.Charts.Inactive", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Title {
            get {
                return ResourceManager.GetString("UserStatsPage.Title", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Subtitle {
            get {
                return ResourceManager.GetString("UserStatsPage.Subtitle", resourceCulture);
            }
        }
        
        public static string UserStatsPage_SeriesProgress_Title {
            get {
                return ResourceManager.GetString("UserStatsPage.SeriesProgress.Title", resourceCulture);
            }
        }
        
        public static string UserStatsPage_SeriesProgress_Completed {
            get {
                return ResourceManager.GetString("UserStatsPage.SeriesProgress.Completed", resourceCulture);
            }
        }
        
        public static string UserStatsPage_SeriesProgress_InProgress {
            get {
                return ResourceManager.GetString("UserStatsPage.SeriesProgress.InProgress", resourceCulture);
            }
        }
        
        public static string UserStatsPage_SeriesProgress_Remaining {
            get {
                return ResourceManager.GetString("UserStatsPage.SeriesProgress.Remaining", resourceCulture);
            }
        }
        
        public static string UserStatsPage_ChaptersProgress_Title {
            get {
                return ResourceManager.GetString("UserStatsPage.ChaptersProgress.Title", resourceCulture);
            }
        }
        
        public static string UserStatsPage_ChaptersProgress_Read {
            get {
                return ResourceManager.GetString("UserStatsPage.ChaptersProgress.Read", resourceCulture);
            }
        }
        
        public static string UserStatsPage_ChaptersProgress_Remaining {
            get {
                return ResourceManager.GetString("UserStatsPage.ChaptersProgress.Remaining", resourceCulture);
            }
        }
        
        public static string UserStatsPage_RankDistribution_Title {
            get {
                return ResourceManager.GetString("UserStatsPage.RankDistribution.Title", resourceCulture);
            }
        }
        
        public static string UserStatsPage_ReadsPerDay_Title {
            get {
                return ResourceManager.GetString("UserStatsPage.ReadsPerDay.Title", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_Completed {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.Completed", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_InProgress {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.InProgress", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_Remaining {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.Remaining", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_Read {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.Read", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_RemainingChapters {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.RemainingChapters", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_SeriesCount {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.SeriesCount", resourceCulture);
            }
        }
        
        public static string UserStatsPage_Charts_DailyReads {
            get {
                return ResourceManager.GetString("UserStatsPage.Charts.DailyReads", resourceCulture);
            }
        }
        
        public static string TagPage_Management {
            get {
                return ResourceManager.GetString("TagPage.Management", resourceCulture);
            }
        }
        
        public static string TagPage_Count {
            get {
                return ResourceManager.GetString("TagPage.Count", resourceCulture);
            }
        }
        
        public static string TagPage_NewTag {
            get {
                return ResourceManager.GetString("TagPage.NewTag", resourceCulture);
            }
        }
        
        public static string TagPage_NoTags {
            get {
                return ResourceManager.GetString("TagPage.NoTags", resourceCulture);
            }
        }
        
        public static string TagPage_NoTags_Description {
            get {
                return ResourceManager.GetString("TagPage.NoTags.Description", resourceCulture);
            }
        }
        
        public static string TagPage_CreateFirst {
            get {
                return ResourceManager.GetString("TagPage.CreateFirst", resourceCulture);
            }
        }
        
        public static string TagPage_List {
            get {
                return ResourceManager.GetString("TagPage.List", resourceCulture);
            }
        }
        
        public static string TagPage_DefaultName {
            get {
                return ResourceManager.GetString("TagPage.DefaultName", resourceCulture);
            }
        }
        
        public static string TagPage_CreateError {
            get {
                return ResourceManager.GetString("TagPage.CreateError", resourceCulture);
            }
        }
        
        public static string TagPage_UpdateError {
            get {
                return ResourceManager.GetString("TagPage.UpdateError", resourceCulture);
            }
        }
        
        public static string TagPage_DeleteError {
            get {
                return ResourceManager.GetString("TagPage.DeleteError", resourceCulture);
            }
        }
        
        public static string UserPage_Management {
            get {
                return ResourceManager.GetString("UserPage.Management", resourceCulture);
            }
        }
        
        public static string UserPage_Count {
            get {
                return ResourceManager.GetString("UserPage.Count", resourceCulture);
            }
        }
        
        public static string UserPage_Add {
            get {
                return ResourceManager.GetString("UserPage.Add", resourceCulture);
            }
        }
        
        public static string UserPage_NoUsers {
            get {
                return ResourceManager.GetString("UserPage.NoUsers", resourceCulture);
            }
        }
        
        public static string UserPage_NoUsers_Description {
            get {
                return ResourceManager.GetString("UserPage.NoUsers.Description", resourceCulture);
            }
        }
        
        public static string UserPage_CreateFirst {
            get {
                return ResourceManager.GetString("UserPage.CreateFirst", resourceCulture);
            }
        }
        
        public static string UserPage_List {
            get {
                return ResourceManager.GetString("UserPage.List", resourceCulture);
            }
        }
        
        public static string UserPage_Permissions {
            get {
                return ResourceManager.GetString("UserPage.Permissions", resourceCulture);
            }
        }
        
        public static string UserPage_CreateError {
            get {
                return ResourceManager.GetString("UserPage.CreateError", resourceCulture);
            }
        }
        
        public static string UserPage_DeleteError {
            get {
                return ResourceManager.GetString("UserPage.DeleteError", resourceCulture);
            }
        }
        
        public static string UserPage_UpdatePermissionsError {
            get {
                return ResourceManager.GetString("UserPage.UpdatePermissionsError", resourceCulture);
            }
        }
        
        public static string LibraryCreatePopup_NewLibrary {
            get {
                return ResourceManager.GetString("LibraryCreatePopup.NewLibrary", resourceCulture);
            }
        }
        
        public static string LibraryCreatePopup_Description {
            get {
                return ResourceManager.GetString("LibraryCreatePopup.Description", resourceCulture);
            }
        }
        
        public static string LibraryCreatePopup_Name {
            get {
                return ResourceManager.GetString("LibraryCreatePopup.Name", resourceCulture);
            }
        }
        
        public static string LibraryCreatePopup_Name_Placeholder {
            get {
                return ResourceManager.GetString("LibraryCreatePopup.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string LibraryCreatePopup_Info {
            get {
                return ResourceManager.GetString("LibraryCreatePopup.Info", resourceCulture);
            }
        }
        
        public static string RankEditPopup_Title {
            get {
                return ResourceManager.GetString("RankEditPopup.Title", resourceCulture);
            }
        }
        
        public static string RankEditPopup_Description {
            get {
                return ResourceManager.GetString("RankEditPopup.Description", resourceCulture);
            }
        }
        
        public static string RankEditPopup_Name {
            get {
                return ResourceManager.GetString("RankEditPopup.Name", resourceCulture);
            }
        }
        
        public static string RankEditPopup_Name_Placeholder {
            get {
                return ResourceManager.GetString("RankEditPopup.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string RankEditPopup_Value {
            get {
                return ResourceManager.GetString("RankEditPopup.Value", resourceCulture);
            }
        }
        
        public static string SavePointCreatePopup_Title {
            get {
                return ResourceManager.GetString("SavePointCreatePopup.Title", resourceCulture);
            }
        }
        
        public static string SavePointCreatePopup_Description {
            get {
                return ResourceManager.GetString("SavePointCreatePopup.Description", resourceCulture);
            }
        }
        
        public static string SavePointCreatePopup_Path {
            get {
                return ResourceManager.GetString("SavePointCreatePopup.Path", resourceCulture);
            }
        }
        
        public static string SavePointCreatePopup_Path_Placeholder {
            get {
                return ResourceManager.GetString("SavePointCreatePopup.Path.Placeholder", resourceCulture);
            }
        }
        
        public static string SavePointCreatePopup_Tip {
            get {
                return ResourceManager.GetString("SavePointCreatePopup.Tip", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Serie_Title {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Serie.Title", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Serie_Description {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Serie.Description", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Serie_Title_Placeholder {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Serie.Title.Placeholder", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Serie_Description_Placeholder {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Serie.Description.Placeholder", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Status {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Status", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Library {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Library", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Tags {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Tags", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Tags_Placeholder {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Tags.Placeholder", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_NoTags {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.NoTags", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Title {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Title", resourceCulture);
            }
        }
        
        public static string SerieUpdatePopup_Description {
            get {
                return ResourceManager.GetString("SerieUpdatePopup.Description", resourceCulture);
            }
        }
        
        public static string TagEditPopup_Title {
            get {
                return ResourceManager.GetString("TagEditPopup.Title", resourceCulture);
            }
        }
        
        public static string TagEditPopup_Description {
            get {
                return ResourceManager.GetString("TagEditPopup.Description", resourceCulture);
            }
        }
        
        public static string TagEditPopup_Name {
            get {
                return ResourceManager.GetString("TagEditPopup.Name", resourceCulture);
            }
        }
        
        public static string TagEditPopup_Name_Placeholder {
            get {
                return ResourceManager.GetString("TagEditPopup.Name.Placeholder", resourceCulture);
            }
        }
        
        public static string TagEditPopup_Color {
            get {
                return ResourceManager.GetString("TagEditPopup.Color", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Title {
            get {
                return ResourceManager.GetString("UserCreatePopup.Title", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Description {
            get {
                return ResourceManager.GetString("UserCreatePopup.Description", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Username {
            get {
                return ResourceManager.GetString("UserCreatePopup.Username", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Username_Placeholder {
            get {
                return ResourceManager.GetString("UserCreatePopup.Username.Placeholder", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Password {
            get {
                return ResourceManager.GetString("UserCreatePopup.Password", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Password_Placeholder {
            get {
                return ResourceManager.GetString("UserCreatePopup.Password.Placeholder", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Role {
            get {
                return ResourceManager.GetString("UserCreatePopup.Role", resourceCulture);
            }
        }
        
        public static string UserCreatePopup_Tip {
            get {
                return ResourceManager.GetString("UserCreatePopup.Tip", resourceCulture);
            }
        }
        
        public static string ConfirmCancelPopup_Confirm {
            get {
                return ResourceManager.GetString("ConfirmCancelPopup.Confirm", resourceCulture);
            }
        }
        
        public static string ConfirmCancelPopup_Cancel {
            get {
                return ResourceManager.GetString("ConfirmCancelPopup.Cancel", resourceCulture);
            }
        }
        
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow.Title", resourceCulture);
            }
        }
        
        public static string MainWindow_Home {
            get {
                return ResourceManager.GetString("MainWindow.Home", resourceCulture);
            }
        }
        
        public static string MainWindow_Libraries {
            get {
                return ResourceManager.GetString("MainWindow.Libraries", resourceCulture);
            }
        }
        
        public static string MainWindow_Admin {
            get {
                return ResourceManager.GetString("MainWindow.Admin", resourceCulture);
            }
        }
        
        public static string MainWindow_Issues {
            get {
                return ResourceManager.GetString("MainWindow.Issues", resourceCulture);
            }
        }
        
        public static string MainWindow_Users {
            get {
                return ResourceManager.GetString("MainWindow.Users", resourceCulture);
            }
        }
        
        public static string MainWindow_Ranks {
            get {
                return ResourceManager.GetString("MainWindow.Ranks", resourceCulture);
            }
        }
        
        public static string MainWindow_Tags {
            get {
                return ResourceManager.GetString("MainWindow.Tags", resourceCulture);
            }
        }
        
        public static string MainWindow_Parameters {
            get {
                return ResourceManager.GetString("MainWindow.Parameters", resourceCulture);
            }
        }
        
        public static string MainWindow_Stats {
            get {
                return ResourceManager.GetString("MainWindow.Stats", resourceCulture);
            }
        }
        
        public static string MainWindow_Stats_User {
            get {
                return ResourceManager.GetString("MainWindow.Stats.User", resourceCulture);
            }
        }
        
        public static string MainWindow_Stats_Server {
            get {
                return ResourceManager.GetString("MainWindow.Stats.Server", resourceCulture);
            }
        }
        
        public static string MainWindow_Parameters_UI {
            get {
                return ResourceManager.GetString("MainWindow.Parameters.UI", resourceCulture);
            }
        }
        
        public static string MainWindow_Logout {
            get {
                return ResourceManager.GetString("MainWindow.Logout", resourceCulture);
            }
        }
        
        public static string MainWindow_RunningTasks {
            get {
                return ResourceManager.GetString("MainWindow.RunningTasks", resourceCulture);
            }
        }
        
        public static string MainWindow_Parameters_Server {
            get {
                return ResourceManager.GetString("MainWindow.Parameters.Server", resourceCulture);
            }
        }
    }
}
