//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManaxClient.Assets.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ManaxClient.Assets.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login.Title", resourceCulture);
            }
        }
        
        internal static string Login_Subtitle {
            get {
                return ResourceManager.GetString("Login.Subtitle", resourceCulture);
            }
        }
        
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login.Username", resourceCulture);
            }
        }
        
        internal static string Login_Username_Placeholder {
            get {
                return ResourceManager.GetString("Login.Username.Placeholder", resourceCulture);
            }
        }
        
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login.Password", resourceCulture);
            }
        }
        
        internal static string Login_Password_Placeholder {
            get {
                return ResourceManager.GetString("Login.Password.Placeholder", resourceCulture);
            }
        }
        
        internal static string Login_Server {
            get {
                return ResourceManager.GetString("Login.Server", resourceCulture);
            }
        }
        
        internal static string Login_Server_Placeholder {
            get {
                return ResourceManager.GetString("Login.Server.Placeholder", resourceCulture);
            }
        }
        
        internal static string Login_SignIn {
            get {
                return ResourceManager.GetString("Login.SignIn", resourceCulture);
            }
        }
        
        internal static string Login_Tip_Title {
            get {
                return ResourceManager.GetString("Login.Tip.Title", resourceCulture);
            }
        }
        
        internal static string Login_Tip_Message {
            get {
                return ResourceManager.GetString("Login.Tip.Message", resourceCulture);
            }
        }
    }
}
