name: CI/CD

on:
  push:
    branches:
      - '**'  # Trigger on push to all branches
  pull_request:
    branches:
      - '**'  # Trigger on pull requests to all branches

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore Manax.sln
    
    - name: Build solution
      run: dotnet build Manax.sln --configuration Release --no-restore
    
    - name: Run tests
      run: dotnet test Manax.sln --configuration Release --no-build --verbosity normal